name: Build and Test

run-name: Build and Test action initiated by ${{ github.actor }}

on: [push, pull_request]

jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Install Node.js ğŸ”§
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm ğŸ”¨
        # https://github.com/pnpm/action-setup
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 7.15.0

      - name: Get pnpm store directory ğŸ—‚ï¸
        # https://github.com/pnpm/action-setup#use-cache-to-reduce-installation-time
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache ğŸ—„ï¸
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles("**/pnpm-lock.yaml") }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies ğŸ”©
        run: pnpm install

      - name: Build and Test ğŸ‘·ğŸ§‘â€ğŸ”¬
        run: pnpm build
