name: Build and Test

run-name: Build and Test action initiated by ${{ github.actor }}

on: [push, pull_request]

jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Install Node.js ğŸ”§
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install Dependencies ğŸ”©
        run: yarn install

      - name: Build ğŸ‘·
        run: yarn build

      - name: Test ğŸ§‘â€ğŸ”¬
        run: yarn test

      - name: Lint ğŸ§‘â€ğŸ”§
        run: yarn lint
