name: Unit Test PR

run-name: Unit Test PR action initiated by ${{ github.actor }}

on:
  pull_request:
    branches: main

jobs:
  test-pr:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Java ğŸ”§
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17

      - name: Install Node.js ğŸ”§
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install Dependencies ğŸ”©
        run: yarn install --frozen-lockfile

      - name: Unit Test Commits ğŸ§‘â€ğŸ”¬
        run: |
          PR_OWNER="${{ github.event.pull_request.head.repo.owner.login }}"
          PR_REPO="${{ github.event.pull_request.head.repo.name }}"
          PR_BRANCH="${{ github.head_ref }}"

          git remote add pr https://github.com/$PR_OWNER/$PR_REPO.git
          git fetch pr $PR_BRANCH

          BASE_SHA=$(git rev-parse ${{ github.event.pull_request.base.sha }})
          HEAD_SHA=$(git rev-parse ${{ github.event.pull_request.head.sha }})

          git rev-list $BASE_SHA..$HEAD_SHA | while read commit; do
            git checkout $commit
            yarn test:commit || exit 1
          done
